### ISSUE TITLE
Issue running automated tests.

### ISSUE THREAD

**Issue by bartbkr** [safarijv/django-qunit-ci#8]
I am running Python 3.5 with Django 1.9. I am able to run and see test results with:
```bash
python manage.py runserver
```
and then navigating to [127.0.0.1:8000/qunit/](127.0.0.1:8000/qunit).

When attempting to run them automated with
```bash
python manage.py selenium
```
or
```bash
python manage.py test
```
I get the following error in the log

```
POST http://127.0.0.1:47481/session {"requiredCapabilities": {}, "desiredCapabilities": {"browserName": "chrome", "platform": "ANY", "version": "", "javascriptEnabled": true, "chromeOptions": {"args": [], "extensions": []}}}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/timeouts {"type": "page load", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "ms": 10000.0}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/url {"url": "http://localhost:8081/qunit/test/?class=qunit.test_model_create.TestListSelectorInstantiate", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac"}
[01/Sep/2016 11:29:00] "GET /qunit/test/?class=qunit.test_model_create.TestListSelectorInstantiate HTTP/1.1" 200 1919
[01/Sep/2016 11:29:00] "GET /qunit/test/?class=qunit.test_model_create.TestListSelectorInstantiate HTTP/1.1" 200 1919
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python3.5/wsgiref/handlers.py", line 137, in run
  File "/usr/lib64/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    self.result = application(self.environ, self.start_response)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1193, in __call__
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1193, in __call__
    return super(FSFilesHandler, self).__call__(environ, start_response)
    return super(FSFilesHandler, self).__call__(environ, start_response)
  File "~/path/.venv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
  File "~/path/.venv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
    response = self.get_response(request)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1176, in get_response
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1176, in get_response
    return self.serve(request)
    return self.serve(request)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1188, in serve
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1188, in serve
    return serve(request, final_rel_path, document_root=self.get_base_dir())
    return serve(request, final_rel_path, document_root=self.get_base_dir())
  File "~/path/.venv/lib/python3.5/site-packages/django/views/static.py", line 54, in serve
  File "~/path/.venv/lib/python3.5/site-packages/django/views/static.py", line 54, in serve
    fullpath = os.path.join(document_root, newpath)
    fullpath = os.path.join(document_root, newpath)
  File "~/path/.venv/lib/python3.5/posixpath.py", line 89, in join
  File "~/path/.venv/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
    genericpath._check_arg_types('join', a, *p)
  File "~/path/.venv/lib/python3.5/genericpath.py", line 143, in _check_arg_types
  File "~/path/.venv/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
TypeError: join() argument must be str or bytes, not 'NoneType'
[01/Sep/2016 11:29:00] "GET /static/qunit.css HTTP/1.1" 500 59
[01/Sep/2016 11:29:00] "GET /static/qunit.css HTTP/1.1" 500 59
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python3.5/wsgiref/handlers.py", line 137, in run
  File "/usr/lib64/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    self.result = application(self.environ, self.start_response)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1193, in __call__
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1193, in __call__
    return super(FSFilesHandler, self).__call__(environ, start_response)
    return super(FSFilesHandler, self).__call__(environ, start_response)
  File "~/path/.venv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
  File "~/path/.venv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
    response = self.get_response(request)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1176, in get_response
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1176, in get_response
    return self.serve(request)
    return self.serve(request)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1188, in serve
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1188, in serve
    return serve(request, final_rel_path, document_root=self.get_base_dir())
    return serve(request, final_rel_path, document_root=self.get_base_dir())
  File "~/path/.venv/lib/python3.5/site-packages/django/views/static.py", line 54, in serve
  File "~/path/.venv/lib/python3.5/site-packages/django/views/static.py", line 54, in serve
    fullpath = os.path.join(document_root, newpath)
    fullpath = os.path.join(document_root, newpath)
  File "~/path/.venv/lib/python3.5/posixpath.py", line 89, in join
  File "~/path/.venv/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
    genericpath._check_arg_types('join', a, *p)
  File "~/path/.venv/lib/python3.5/genericpath.py", line 143, in _check_arg_types
  File "~/path/.venv/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
TypeError: join() argument must be str or bytes, not 'NoneType'
[01/Sep/2016 11:29:00] "GET /static/qunit.js HTTP/1.1" 500 59
[01/Sep/2016 11:29:00] "GET /static/qunit.js HTTP/1.1" 500 59
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python3.5/wsgiref/handlers.py", line 137, in run
  File "/usr/lib64/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    self.result = application(self.environ, self.start_response)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1193, in __call__
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1193, in __call__
    return super(FSFilesHandler, self).__call__(environ, start_response)
    return super(FSFilesHandler, self).__call__(environ, start_response)
  File "~/path/.venv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
  File "~/path/.venv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
    response = self.get_response(request)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1176, in get_response
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1176, in get_response
    return self.serve(request)
    return self.serve(request)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1188, in serve
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1188, in serve
    return serve(request, final_rel_path, document_root=self.get_base_dir())
    return serve(request, final_rel_path, document_root=self.get_base_dir())
  File "~/path/.venv/lib/python3.5/site-packages/django/views/static.py", line 54, in serve
  File "~/path/.venv/lib/python3.5/site-packages/django/views/static.py", line 54, in serve
    fullpath = os.path.join(document_root, newpath)
    fullpath = os.path.join(document_root, newpath)
  File "~/path/.venv/lib/python3.5/posixpath.py", line 89, in join
  File "~/path/.venv/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
    genericpath._check_arg_types('join', a, *p)
  File "~/path/.venv/lib/python3.5/genericpath.py", line 143, in _check_arg_types
  File "~/path/.venv/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
TypeError: join() argument must be str or bytes, not 'NoneType'
[01/Sep/2016 11:29:00] "GET /static/qunit-config.js HTTP/1.1" 500 59
[01/Sep/2016 11:29:00] "GET /static/qunit-config.js HTTP/1.1" 500 59
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python3.5/wsgiref/handlers.py", line 137, in run
  File "/usr/lib64/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    self.result = application(self.environ, self.start_response)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1193, in __call__
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1193, in __call__
    return super(FSFilesHandler, self).__call__(environ, start_response)
    return super(FSFilesHandler, self).__call__(environ, start_response)
  File "~/path/.venv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
  File "~/path/.venv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
    response = self.get_response(request)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1176, in get_response
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1176, in get_response
    return self.serve(request)
    return self.serve(request)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1188, in serve
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1188, in serve
    return serve(request, final_rel_path, document_root=self.get_base_dir())
    return serve(request, final_rel_path, document_root=self.get_base_dir())
  File "~/path/.venv/lib/python3.5/site-packages/django/views/static.py", line 54, in serve
  File "~/path/.venv/lib/python3.5/site-packages/django/views/static.py", line 54, in serve
    fullpath = os.path.join(document_root, newpath)
    fullpath = os.path.join(document_root, newpath)
  File "~/path/.venv/lib/python3.5/posixpath.py", line 89, in join
  File "~/path/.venv/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
    genericpath._check_arg_types('join', a, *p)
  File "~/path/.venv/lib/python3.5/genericpath.py", line 143, in _check_arg_types
  File "~/path/.venv/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
TypeError: join() argument must be str or bytes, not 'NoneType'
[01/Sep/2016 11:29:00] "GET /static/shared_static/js/jquery-1.12.3.min.js HTTP/1.1" 500 59
[01/Sep/2016 11:29:00] "GET /static/shared_static/js/jquery-1.12.3.min.js HTTP/1.1" 500 59
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python3.5/wsgiref/handlers.py", line 137, in run
  File "/usr/lib64/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    self.result = application(self.environ, self.start_response)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1193, in __call__
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1193, in __call__
    return super(FSFilesHandler, self).__call__(environ, start_response)
    return super(FSFilesHandler, self).__call__(environ, start_response)
  File "~/path/.venv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
  File "~/path/.venv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
    response = self.get_response(request)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1176, in get_response
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1176, in get_response
    return self.serve(request)
    return self.serve(request)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1188, in serve
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1188, in serve
    return serve(request, final_rel_path, document_root=self.get_base_dir())
    return serve(request, final_rel_path, document_root=self.get_base_dir())
  File "~/path/.venv/lib/python3.5/site-packages/django/views/static.py", line 54, in serve
  File "~/path/.venv/lib/python3.5/site-packages/django/views/static.py", line 54, in serve
    fullpath = os.path.join(document_root, newpath)
    fullpath = os.path.join(document_root, newpath)
  File "~/path/.venv/lib/python3.5/posixpath.py", line 89, in join
  File "~/path/.venv/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
    genericpath._check_arg_types('join', a, *p)
  File "~/path/.venv/lib/python3.5/genericpath.py", line 143, in _check_arg_types
  File "~/path/.venv/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
TypeError: join() argument must be str or bytes, not 'NoneType'
[01/Sep/2016 11:29:00] "GET /static/model_admin/js/ListSelector.js HTTP/1.1" 500 59
[01/Sep/2016 11:29:00] "GET /static/model_admin/js/ListSelector.js HTTP/1.1" 500 59
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python3.5/wsgiref/handlers.py", line 137, in run
  File "/usr/lib64/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    self.result = application(self.environ, self.start_response)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1193, in __call__
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1193, in __call__
    return super(FSFilesHandler, self).__call__(environ, start_response)
    return super(FSFilesHandler, self).__call__(environ, start_response)
  File "~/path/.venv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
  File "~/path/.venv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
    response = self.get_response(request)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1176, in get_response
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1176, in get_response
    return self.serve(request)
    return self.serve(request)
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1188, in serve
  File "~/path/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 1188, in serve
    return serve(request, final_rel_path, document_root=self.get_base_dir())
    return serve(request, final_rel_path, document_root=self.get_base_dir())
  File "~/path/.venv/lib/python3.5/site-packages/django/views/static.py", line 54, in serve
  File "~/path/.venv/lib/python3.5/site-packages/django/views/static.py", line 54, in serve
    fullpath = os.path.join(document_root, newpath)
    fullpath = os.path.join(document_root, newpath)
  File "~/path/.venv/lib/python3.5/posixpath.py", line 89, in join
  File "~/path/.venv/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
    genericpath._check_arg_types('join', a, *p)
  File "~/path/.venv/lib/python3.5/genericpath.py", line 143, in _check_arg_types
  File "~/path/.venv/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
TypeError: join() argument must be str or bytes, not 'NoneType'
[01/Sep/2016 11:29:00] "GET /static/model_admin/js/tests/list_selector_instantiate.js HTTP/1.1" 500 59
[01/Sep/2016 11:29:00] "GET /static/model_admin/js/tests/list_selector_instantiate.js HTTP/1.1" 500 59
Not Found: /favicon.ico
Not Found: /favicon.ico
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
[01/Sep/2016 11:29:00] "GET /favicon.ico HTTP/1.1" 404 85
[01/Sep/2016 11:29:00] "GET /favicon.ico HTTP/1.1" 404 85
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
POST http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac/execute {"script": "return QUnit.Django.ready", "sessionId": "dd56a649f428009ddcbc58a1ce14ebac", "args": []}
Finished Request
DELETE http://127.0.0.1:47481/session/dd56a649f428009ddcbc58a1ce14ebac {"sessionId": "dd56a649f428009ddcbc58a1ce14ebac"}
Finished Request
"chromeOp
```

I've modified the explict paths for privacy. I was also having some trouble getting everything running on my setup. It may be a Python 3.5 issue, but I'm not sure. My changes are in this fork: [https://github.com/bartbkr/sbo-selenium](https://github.com/bartbkr/sbo-selenium), which I made to sbo-selenium.

**Comment by bartbkr** [comment]
Is there any other information that might be helpful from my standpoint? I'm happy to work out some of the issues with this if you could lead me in the right direction and develop a pull request.

**Comment by bartbkr** [comment]
Hi, this error was driven by the fact that I wasn't serving the static files for the unit-tests. I am no longer having this issue.
